### ISSUE TITLE
[BUG] Plex: Failed to login, Error: No connection adapters were found

### ISSUE THREAD

**Issue by tejasgadhia** [luigi311/JellyPlex-Watched#104]
**Describe the bug**
Upon initial start, getting this error in my log. 

**To Reproduce**
Docker Compose:
```
  jellyplex-watched:
    image: luigi311/jellyplex-watched:latest
    container_name: jellyplex-watched
    restart: always
    volumes:
      - ${DOCKER_CONF_DIR}/jellyplex-watched:/config
    environment:
      - DRYRUN=True
      - DEBUG=True
      - DEBUG_LEVEL=info
      - RUN_ONLY_ONCE=False
      - SLEEP_DURATION=3600
      - LOGFILE=/config/log.log
      - LIBRARY_MAPPING={"TV Shows":"Television", "TV Shows - Foreign":"TV - Foreign"}
      - USER_MAPPING=
      # - BLACKLIST_LIBRARY=
      # - WHITELIST_LIBRARY=
      # - BLACKLIST_LIBRARY_TYPE=
      # - WHITELIST_LIBRARY_TYPE=
      # - BLACKLIST_USERS=
      # - WHITELIST_USERS=
      - PLEX_BASEURL="http://192.168.1.32:32400"
      - PLEX_TOKEN="XXXXXXXXXX
      - JELLYFIN_BASEURL="http://192.168.1.36:8096"
      - JELLYFIN_TOKEN="XXXXXXXXXX"
      - SSL_BYPASS=True
      - SYNC_FROM_PLEX_TO_JELLYFIN=True
      - SYNC_FROM_JELLYFIN_TO_PLEX=False
      - SYNC_FROM_PLEX_TO_PLEX=False
      - SYNC_FROM_JELLYFIN_TO_JELLYFIN=False
```

**Expected behavior**
Expecting application to start up successfully.

**Logs**
```
[ERROR]: Plex: Failed to login, Error: No connection adapters were found for '"http://192.168.1.32:32400"/'
[ERROR]: No connection adapters were found for '"http://192.168.1.32:32400"/'
[ERROR]: Traceback (most recent call last):
  File "/app/src/plex.py", line 400, in login
    plex = PlexServer(baseurl, token, session=self.session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/server.py", line 115, in __init__
    data = self.query(self.key, timeout=self._timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/server.py", line 745, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 794, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for '"http://192.168.1.32:32400"/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/main.py", line 382, in main
    main_loop()
  File "/app/src/main.py", line 298, in main_loop
    servers = generate_server_connections()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/main.py", line 89, in generate_server_connections
    Plex(
  File "/app/src/plex.py", line 393, in __init__
    self.plex = self.login(self.baseurl, self.token)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/plex.py", line 415, in login
    raise Exception(e)
Exception: No connection adapters were found for '"http://192.168.1.32:32400"/'

Retrying in 3600.0
```

**Type:**
- [ Yes ] Docker 
- [ No ] Native

**Additional context**

**Comment by nebb00** [comment]
i got the same issue

**Comment by luigi311** [comment]
I think it’s an issue with the compose setup. Might be similar to #97

**Comment by nebb00** [comment]
> I think it’s an issue with the compose setup. Might be similar to #97

I tried using the env file. And had the same error only ever picking up one of the servers. Have two Plex servers. 

Tried literally every combo I could think off

**Comment by luigi311** [comment]
Did you set docker compose like so? https://github.com/luigi311/JellyPlex-Watched/issues/59#issuecomment-1493399698

**Comment by tejasgadhia** [comment]
> Did you set docker compose like so? [#59 (comment)](https://github.com/luigi311/JellyPlex-Watched/issues/59#issuecomment-1493399698)

I did not try using a separate env file, I was following the template here: https://github.com/luigi311/JellyPlex-Watched/blob/main/docker-compose.yml

Will try an env file and report back.

**Comment by nebb00** [comment]
> Did you set docker compose like so? [#59 (comment)](https://github.com/luigi311/JellyPlex-Watched/issues/59#issuecomment-1493399698)

Very similar to the first one. I know it was reading the file. But had the same error as setting via compose

**Comment by luigi311** [comment]
Interesting. I would say just try running it from straight docker for now and I’ll see if I can replicate this again and make some changes. I don’t really use docker compose so its not really tested that often

**Comment by nebb00** [comment]
> Interesting. I would say just try running it from straight docker for now and I’ll see if I can replicate this again and make some changes. I don’t really use docker compose so its not really tested that often

Not sure why the env file was not working for me then. Just wouldn't pick up both Plex servers.

**Comment by luigi311** [comment]
In docker compose i only get this if i add in quotes, so for the baseurls and the tokens do not use any quotes and just put in your url and tokens as is
