### ISSUE TITLE
[ERROR]: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by thereallouise** [luigi311/JellyPlex-Watched#110]
**Describe the bug**
Bug/error happens when launching application via Docker UI in unraid.

**To Reproduce**
Run app
Open log file
![image](https://github.com/luigi311/JellyPlex-Watched/assets/74062252/f6208d8f-4105-411f-947f-7291ca5caa40)

**Expected behavior**
Application should run

**Logs**
[ERROR]: Expecting value: line 1 column 1 (char 0)
[ERROR]: Traceback (most recent call last):
  File "/app/src/main.py", line 385, in main
    main_loop()
  File "/app/src/main.py", line 261, in main_loop
    user_mapping = json.loads(user_mapping.lower())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Retrying in 3600.0

**Type:**
- [ ] Docker Compose
- [X] Docker
- [ ] Native

**Additional context**

**Comment by andrewm659** [comment]
Also running into the same issue using Docker on AlmaLinux 9.x with privileged mode enabled.

**Comment by ggrensteiner** [comment]
Same issue with docker-compose on ubuntu 20 server.

**Comment by louiseuk** [comment]
Thanks, luigi.
I'm running off an UNRAID template - Container Variable: USER_MAPPING
louise.uk:louise (first is plex username, second is jellyfin username, but it doesn't matter which order, I get the same error)

**Comment by luigi311** [comment]
Can  you try
{"louise.uk":"louise"}

**Comment by luigi311** [comment]
unfortunately this isnt something i can replicate when i put in what i told you. If i put it in without the curly braces i get the same error but it works perfectly fine when i copy and paste in 
 {"louise.uk":"louise"}

**Comment by andrewm659** [comment]
I am using portainer and can't get the docker-compose.  I didn't make it a stack.

**Comment by exxrxxe** [comment]
I was receiving the same error in Unraid that started this issue and successful fixed my issue utilizing {"user1":"user11"}
