### ISSUE TITLE
[BUG] Query failed with status 500 Internal Server Error syning from Plex to Jellyfin

### ISSUE THREAD

**Issue by JunkKnight** [luigi311/JellyPlex-Watched#118]
**Describe the bug**
I'm trying to sync from Plex to Jellyfin but it errors out when actually running the sync.

**To Reproduce**
Set dryrun to false, and let it sync. Error occurs after it builds the list of items that need to be marked.

**Logs**
`Movies: {}
[INFO]: Jellyfin: Updating watched for Jellyfin_Username in library TV Shows for show Agatha Christie's Poirot
[INFO]: Jellyfin: Updating watched for Jellyfin_Username in library Anime for show 86: Eighty Six
[MARK]: Jellyfin: 86: Eighty Six Season 1 Episode 1 Undertaker as watched for Jellyfin_Username in Anime
[ERROR]: Jellyfin: Query post /Users/57125e5594fa4570a29b3e109f401977/PlayedItems/07345be6a1dc6a475359d3d77825a8e1
Results None
Query failed with status 500 Internal Server Error
[ERROR]: Jellyfin: Error updating watched for Jellyfin_Username in library Anime, Query failed with status 500 Internal Server Error
[ERROR]: Traceback (most recent call last):
  File "/app/src/jellyfin.py", line 128, in query
    raise Exception(
Exception: Query failed with status 500 Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/jellyfin.py", line 826, in update_user_watched
    await self.query(
  File "/app/src/jellyfin.py", line 144, in query
    raise Exception(e)
Exception: Query failed with status 500 Internal Server Error

[MARK]: Jellyfin: Agatha Christie's Poirot Season 1 Episode 1 The Adventure of the Clapham Cook as watched for Jellyfin_Username in TV Shows
[ERROR]: Jellyfin: Query post /Users/57125e5594fa4570a29b3e109f401977/PlayedItems/be4cbe3c161e6fb5a1821f70ac297d5e
Results None
Query failed with status 500 Internal Server Error
[ERROR]: Jellyfin: Error updating watched for Jellyfin_Username in library TV Shows, Query failed with status 500 Internal Server Error
[ERROR]: Traceback (most recent call last):
  File "/app/src/jellyfin.py", line 128, in query
    raise Exception(
Exception: Query failed with status 500 Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/jellyfin.py", line 826, in update_user_watched
    await self.query(
  File "/app/src/jellyfin.py", line 144, in query
    raise Exception(e)
Exception: Query failed with status 500 Internal Server Error

[MARK]: Jellyfin: The Adjustment Bureau as watched for Jellyfin_Username in Movies
[ERROR]: Jellyfin: Query post /Users/57125e5594fa4570a29b3e109f401977/PlayedItems/44be74b5b381765458a69cc24316d242
Results None
Query failed with status 500 Internal Server Error
[ERROR]: Jellyfin: Error updating watched for Jellyfin_Username in library Movies, Query failed with status 500 Internal Server Error
[ERROR]: Traceback (most recent call last):
  File "/app/src/jellyfin.py", line 128, in query
    raise Exception(
Exception: Query failed with status 500 Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/jellyfin.py", line 643, in update_user_watched
    await self.query(
  File "/app/src/jellyfin.py", line 144, in query
    raise Exception(e)
Exception: Query failed with status 500 Internal Server Error`

Before this it shows in the logs a large list of episode names/numbers I've omitted since it's huge. I also censored my Jellyfin username, but it shows correctly in the logs.

**Type:**
- [ ] Docker Compose
- [ *] Docker
- [ ] Unraid
- [ ] Native

**Additional context**
It seems to correctly establish a connection to both servers, and dryrun=true passes with out any issues.

**Comment by luigi311** [comment]
Can you try the new updates, i removed async from jellyfin since it was causing issues and didnt really speed it up.

**Comment by jonoscott** [comment]
I've got similar issues to this,  I'm using it in Docker (not Unraid).
Running with Dryrun on, it shows as everything ok with marking the episodes as watched,  but turm the dryrun to false and it fails with the following
2025-06-26 02:41:02.071 | INFO     | src.main:main_loop:116 - Dryrun: False
2025-06-26 02:41:02.072 | INFO     | src.main:main_loop:122 - User Mapping: {'jellyfinAccountName': 'MyPlexAccountName'}
2025-06-26 02:41:02.072 | INFO     | src.main:main_loop:128 - Library Mapping: {'Shows': 'TV Shows'}
2025-06-26 02:41:02.072 | INFO     | src.main:main_loop:131 - Creating (black/white)lists
2025-06-26 02:41:02.073 | INFO     | src.main:main_loop:162 - Creating server connections
2025-06-26 02:41:03.736 | INFO     | src.main:main_loop:178 - Server 1: <class 'src.plex.Plex'>: Plex NASBox: 1.41.7.9799-5bce000f7
2025-06-26 02:41:03.738 | INFO     | src.main:main_loop:179 - Server 2: <class 'src.jellyfin.Jellyfin'>: Jellyfin jellyfin: 10.10.7
2025-06-26 02:41:03.739 | INFO     | src.main:main_loop:182 - Creating users list
2025-06-26 02:41:03.739 | INFO     | src.users:setup_users:149 - Server 1 users: [<MyPlexAccount:4151917:MyPlexAccountName>]
2025-06-26 02:41:03.739 | INFO     | src.users:setup_users:150 - Server 2 users: {'Jono': 'MY_USER_ID'}
2025-06-26 02:41:03.816 | INFO     | src.main:main_loop:196 - Server 1 syncing libraries: ['Movies', 'TV Shows']
2025-06-26 02:41:03.817 | INFO     | src.main:main_loop:197 - Server 2 syncing libraries: ['Shows', 'Movies']
2025-06-26 02:41:03.817 | INFO     | src.main:main_loop:199 - Creating watched lists
2025-06-26 02:41:03.817 | INFO     | src.plex:get_user_library_watched:337 - Plex: Generating watched for MyPlexAccountName in library Movies
2025-06-26 02:41:07.882 | INFO     | src.plex:get_user_library_watched:337 - Plex: Generating watched for MyPlexAccountName in library TV Shows
2025-06-26 02:42:22.541 | INFO     | src.main:main_loop:201 - Finished creating watched list server 1
2025-06-26 02:42:22.574 | INFO     | src.jellyfin_emby:get_user_library_watched:290 - Jellyfin: Generating watched for jellyfinAccountName in library Movies
2025-06-26 02:42:22.586 | INFO     | src.jellyfin_emby:get_user_library_watched:414 - Jellyfin: Finished getting watched for jellyfinAccountName in library Movies
2025-06-26 02:42:22.586 | INFO     | src.jellyfin_emby:get_user_library_watched:290 - Jellyfin: Generating watched for jellyfinAccountName in library Shows
2025-06-26 02:42:23.803 | INFO     | src.jellyfin_emby:get_user_library_watched:414 - Jellyfin: Finished getting watched for jellyfinAccountName in library Shows
2025-06-26 02:42:23.805 | INFO     | src.main:main_loop:204 - Finished creating watched list server 2
2025-06-26 02:42:24.021 | INFO     | src.main:main_loop:209 - Cleaning Server 1 Watched
2025-06-26 02:42:24.327 | INFO     | src.main:main_loop:214 - Cleaning Server 2 Watched
2025-06-26 02:42:24.544 | INFO     | src.main:main_loop:227 - Syncing Jellyfin jellyfin: 10.10.7 -> Plex NASBox: 1.41.7.9799-5bce000f7
2025-06-26 02:42:24.546 | INFO     | src.main:main_loop:236 - Syncing Plex NASBox: 1.41.7.9799-5bce000f7 -> Jellyfin jellyfin: 10.10.7
2025-06-26 02:42:24.579 | INFO     | src.jellyfin_emby:update_user_watched:488 - Jellyfin: Updating watched for jellyfinAccountName in library Movies
2025-06-26 02:42:29.082 | ERROR    | src.jellyfin_emby:query:167 - Jellyfin: Query post /Users/MY_USER_ID/PlayedItems/35c9f985236d3cd12e412b386b124c75

Results None
Query failed with status 500 Internal Server Error
2025-06-26 02:42:29.083 | ERROR    | src.jellyfin_emby:update_user_watched:681 - Jellyfin: Error updating watched for jellyfinAccountName in library Movies, Query failed with status 500 Internal Server Error
2025-06-26 02:42:29.101 | INFO     | src.jellyfin_emby:update_watched:745 - Jellyfin: Library TV Shows not found, but Shows found, using Shows
2025-06-26 02:42:29.102 | INFO     | src.jellyfin_emby:update_user_watched:488 - Jellyfin: Updating watched for jellyfinAccountName in library Shows
2025-06-26 02:42:29.418 | ERROR    | src.jellyfin_emby:query:167 - Jellyfin: Query post /Users/MY_USER_ID/PlayedItems/51457265d53faa5eeb55e552d3ef7d9c

Results None
Query failed with status 500 Internal Server Error
2025-06-26 02:42:29.418 | ERROR    | src.jellyfin_emby:update_user_watched:681 - Jellyfin: Error updating watched for Jono in library Shows, Query failed with status 500 Internal Server Error
2025-06-26 02:42:29.436 | INFO     | src.main:main:260 - Average time: 87.3842325489968
2025-06-26 02:42:29.436 | INFO     | src.main:main:265 - Looping in 1800.0


NOTE: I've changed a few things from the actual log,  eg MY_USER_ID,  jellyfinAccountName & MyPlexAccountName

**Comment by luigi311** [comment]
@jonoscott  are you by chance using a reverse proxy or hitting the ip address directly? Most of the time ive see rejections or errors like that its been an issue hitting the public domain instead of directly into the server. If that isnt the case then im not really sure what could be causing the issue. It looks like its only failing when marking something as watched and i changed the endpoint im using in v8.1.0 now so you can try and see if that works instead for you.

**Comment by lennvilardi** [comment]
Same using portainer with the stack option (docker-compose), dryrun true works but dryrun false get error 500
