### ISSUE TITLE
[BUG] Unable to mark on Jellyfin account

### ISSUE THREAD

**Issue by bencmorrison** [luigi311/JellyPlex-Watched#156]
**Describe the bug**
There is an error when attempting to update Jellyfin with Plex's watch statuses for a user.

**To Reproduce**
1. Set up
2. Map Plex user to Jellyfin User
3. Map Movies and TV Shows libraries
4. All syncs turn to true
5. Plex and Jellyfin are behind a reverse proxy that has https
6. Use docker compose with Plex and Jellyfin in docker as well.

**Expected behavior**
```
MARK]: Jellyfin: <MOVIE> as watched for <JELLYFIN USER> in Movies
[ERROR]: Jellyfin: Query post /Users/<uuid>/PlayedItems/<uuid>

Results None
'Response' object has no attribute 'status'
[ERROR]: Jellyfin: Error updating watched for ben in library Movies, 'Response' object has no attribute 'status'
[ERROR]: Traceback (most recent call last):
  File "/app/src/jellyfin.py", line 145, in query
    f"Query failed with status {response.status} {response.reason}"
                                ^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'status'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/src/jellyfin.py", line 584, in update_user_watched
    self.query(
  File "/app/src/jellyfin.py", line 160, in query
    raise Exception(e)
Exception: 'Response' object has no attribute 'status'
[ERROR]: Jellyfin: Error updating watched, 'Response' object has no attribute 'status'
[ERROR]: 'Response' object has no attribute 'status'
[ERROR]: Traceback (most recent call last):
  File "/app/src/jellyfin.py", line 145, in query
    f"Query failed with status {response.status} {response.reason}"
                                ^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'status'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/src/jellyfin.py", line 584, in update_user_watched
    self.query(
  File "/app/src/jellyfin.py", line 160, in query
    raise Exception(e)
Exception: 'Response' object has no attribute 'status'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/src/jellyfin.py", line 836, in update_watched
    self.update_user_watched(
  File "/app/src/jellyfin.py", line 759, in update_user_watched
    raise Exception(e)
Exception: 'Response' object has no attribute 'status'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/src/main.py", line 394, in main
    main_loop()
  File "/app/src/main.py", line 378, in main_loop
    update_server_watched(
  File "/app/src/main.py", line 207, in update_server_watched
    server_connection[1].update_watched(
  File "/app/src/jellyfin.py", line 842, in update_watched
    raise Exception(e)
Exception: 'Response' object has no attribute 'status'
Retrying in 3600.0
```

**Logs**
If applicable, add logs to help explain your problem ideally with DEBUG set to true, be sure to remove sensitive information

**Type:**
- [x] Docker Compose
- [ ] Docker
- [ ] Unraid
- [ ] Native

**Comment by luigi311** [comment]
Are you using jellyfin 10.9?

**Comment by bencmorrison** [comment]
I wasn't! I just pulled the latest docker image and it is working. 
All good here, will close. Ta!
