### ISSUE TITLE
[BUG] KeyError: 'season'

### ISSUE THREAD

**Issue by johanruda** [luigi311/JellyPlex-Watched#163]
Hello hello!

Started getting this a while back. Probably errors out after some Plex update.

2024-04-11 19:55:23 [INFO]: Cleaning Server 2 Watched
2024-04-11 19:55:23 [INFO]: Skipping show_output_dict 
2024-04-11 19:55:23 [INFO]: Skipping episode_output_dict
2024-04-11 19:55:23 [INFO]: Skipping movies_output_dict failed
2024-04-11 19:55:23 [INFO]: Skipping movies_output_dict failed
2024-04-11 19:55:23 [INFO]: Skipping show_output_dict 
2024-04-11 19:55:23 [INFO]: Skipping episode_output_dict
2024-04-11 19:55:23 [INFO]: Skipping show_output_dict 
2024-04-11 19:55:23 [INFO]: Skipping episode_output_dict
2024-04-11 19:55:23 [ERROR]: 'season'
2024-04-11 19:55:23 [ERROR]: Traceback (most recent call last):
2024-04-11 19:55:23   File "/app/src/main.py", line 394, in main
2024-04-11 19:55:23     main_loop()
2024-04-11 19:55:23   File "/app/src/main.py", line 355, in main_loop
2024-04-11 19:55:23     server_2_watched_filtered = cleanup_watched(
2024-04-11 19:55:23                                 ^^^^^^^^^^^^^^^^
2024-04-11 19:55:23   File "/app/src/watched.py", line 129, in cleanup_watched
2024-04-11 19:55:23     filter_episode_watched_list_2_keys_dict(
2024-04-11 19:55:23   File "/app/src/watched.py", line 243, in filter_episode_watched_list_2_keys_dict
2024-04-11 19:55:23     episode_watched_list_2_keys_dict["season"]
2024-04-11 19:55:23     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
2024-04-11 19:55:23 KeyError: 'season'
2024-04-11 19:55:23 
2024-04-11 19:55:23 Retrying in 300.0

**Comment by AaronNybo** [comment]
I am getting the same. Wonder if there any ideas out there for a quick fix?

**Comment by luigi311** [comment]
can you guys try the dev image, i think i got it fixed there

**Comment by gaming09** [comment]
> can you guys try the dev image, i think i got it fixed there

switched to luigi311/jellyplex-watched:dev  

Seems to have resolved the issue

**Comment by luigi311** [comment]
I have merged it up to latest. Glad its working for you guys now
