### ISSUE TITLE
[BUG] Sync fails when Live TV is enabled

### ISSUE THREAD

**Issue by misleadingrhino** [luigi311/JellyPlex-Watched#168]
**Describe the bug**
Process fails out with error 
```
[ERROR]: Jellyfin: Failed to get watched, Error: Conflicting values for subkey 'Live TV' under key '(user removed)'
```

**To Reproduce**
Run sync with Live TV Enabled

**Expected behavior**
Sync to work

**Logs**
Docker Compose
```
  jellyplex-watched:
    image: luigi311/jellyplex-watched:latest
    container_name: jellyplex-watched
    restart: always
    environment:
      - DRYRUN=False
      - DEBUG=True
      - DEBUG_LEVEL=info
      - RUN_ONLY_ONCE=False
      - SLEEP_DURATION=3600
      - LOGFILE=/tmp/log.log
      - MARKFILE=/tmp/mark.log
      - USER_MAPPING={"plex_user":"jellyfin_user"}
      - LIBRARY_MAPPING={"TV Shows":"Shows"}
      - BLACKLIST_LIBRARY=
      - WHITELIST_LIBRARY=
      - BLACKLIST_LIBRARY_TYPE="Live TV"
      - WHITELIST_LIBRARY_TYPE=
      - BLACKLIST_USERS=
      - WHITELIST_USERS=
      - PLEX_BASEURL=(removed}
      - PLEX_TOKEN=$PLEX_TOKEN
      - JELLYFIN_BASEURL=(removed)
      - JELLYFIN_TOKEN=$JELLYPLEX_JELLYFIN_API
      - SSL_BYPASS=True
      - SYNC_FROM_PLEX_TO_JELLYFIN=True
      - SYNC_FROM_JELLYFIN_TO_PLEX=True
      - SYNC_FROM_PLEX_TO_PLEX=False
      - SYNC_FROM_JELLYFIN_TO_JELLYFIN=False
```
Relevant Logs
```
[ERROR]: Jellyfin: Failed to get watched, Error: Conflicting values for subkey 'Live TV' under key 'jellyfin_user'
[ERROR]: Conflicting values for subkey 'Live TV' under key 'jellyfin_user'
[ERROR]: Traceback (most recent call last):
  File "/app/src/jellyfin.py", line 542, in get_watched
    user_watched_combine = combine_watched_dicts(user_watched)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/watched.py", line 25, in combine_watched_dicts
    raise ValueError(
ValueError: Conflicting values for subkey 'Live TV' under key 'jellyfin_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/main.py", line 394, in main
    main_loop()
  File "/app/src/main.py", line 336, in main_loop
    server_2_watched = get_server_watched(
                       ^^^^^^^^^^^^^^^^^^^
  File "/app/src/main.py", line 185, in get_server_watched
    return server_connection[1].get_watched(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/jellyfin.py", line 551, in get_watched
    raise Exception(e)
Exception: Conflicting values for subkey 'Live TV' under key 'jellyfin_user'
```

**Type:**
- [x] Docker Compose
- [ ] Docker
- [ ] Unraid
- [ ] Native

**Comment by misleadingrhino** [comment]
I got around this by whitelisting the TV Shows and Movies library for now.

**Comment by luigi311** [comment]
Interesting i thought i had gotten around this by excluding the type that they use for live tv. I dont have a live tv library though so i was never really able to test it.

**Comment by misleadingrhino** [comment]
As best I can tell, Jellyfin doesn't have a separate library type for Live TV. It seems to be showing up as "Shows."

**Comment by luigi311** [comment]
Can anyone confirm if this is still an issue? A lot has changed on how i grab and merge things
