### ISSUE TITLE
Ignore SSLCertificate

### ISSUE THREAD

**Issue by nitschis** [luigi311/JellyPlex-Watched#20]
Please add an option to ignore non-matching SSL certificates from plex-direct.domain and your local instance.

It is possible to use http when setting "Secure connections:" to “preferred” instead of “always”, but I would rather leave my server on “always”.

Thanks you!

**Comment by Deanosim** [comment]
1+ to this, would be really handy, had a bunch of trouble getting it to connect until I switched my plex server to preferred.

**Comment by bman87** [comment]
1+ thanks!

**Comment by luigi311** [comment]
Last time i tried this i ran into an issue with the plex api. Ill see if i can get it working.

**Comment by luigi311** [comment]
Can you guys try the new dev image with
> SSL_BYPASS = "True"

in your .env and let me know if it works.

**Comment by luigi311** [comment]
This has been resolved via 9ffbc49ad30fb2624b6c983e588c339db554fbd5 you just need to add in that SSL_BYPASS="True" to your .env and it should ignore the ssl errors. Feel free to reopen this ticket if you run into any issues.

**Comment by nitschis** [comment]
Sorry for the super late reply.  I have finally come to tested it. The error seems to be related to the strange "plex.direct URL.

`Jellyfin: Generating watched for lis in library TV Shows
[ERROR]: Plex: Failed to update watched, Error: HTTPSConnectionPool(host='plex', port=32400): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'plex' doesn't match '*.91f97fsa2e5b453bbdd2da10d2df04d3.plex.direct'")))
[ERROR]: HTTPSConnectionPool(host='plex', port=32400): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'plex' doesn't match '*.91f97fea4e5b453bbddd8a10d2df04d3.plex.direct'")))
[ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 467, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 540, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_match_hostname.py", line 155, in match_hostname
    raise CertificateError("hostname %r doesn't match %r" % (hostname, dnsnames[0]))
urllib3.util.ssl_match_hostname.CertificateError: hostname 'plex' doesn't match '*.91f97fea4e5b453bbddd8a10d2df04d3.plex.direct'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='plex', port=32400): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'plex' doesn't match '*.91f97fea4e5b453bbddd8a10d2df04d3.plex.direct'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/plex.py", line 400, in update_watched
    user_plex = PlexServer(
                ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/server.py", line 115, in __init__
    data = self.query(self.key, timeout=self._timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/server.py", line 745, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='plex', port=32400): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'plex' doesn't match '*.91f97fea4e5b453bbddd8a10d2df04d3.plex.direct'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/main.py", line 396, in main
    main_loop()
  File "/app/src/main.py", line 373, in main_loop
    update_server_watched(
  File "/app/src/main.py", line 256, in update_server_watched
    server_connection[1].update_watched(
  File "/app/src/plex.py", line 451, in update_watched
    raise Exception(e)
Exception: HTTPSConnectionPool(host='plex', port=32400): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'plex' doesn't match '*.91f97fea4e5b453bbddd8a10d2df04d3.plex.direct'")))

Retrying in 3600.0
`

**Comment by luigi311** [comment]
Did you download the latest docker image and enable the SSL_BYPASS flag in your config? It looks like it's failing to verify the SSL hostname which should happen with the flag enabled
