### ISSUE TITLE
[BUG]Unraid Logs

### ISSUE THREAD

**Issue by wookie104** [luigi311/JellyPlex-Watched#212]
**Describe the bug**
On Unraid unable to change the LOGILE location from /tmp/log.log (The permissions to the directory are set to Owner, Group, Other all are Read/Write permissions). I am using version 6.1.1 of JellyPlex-Watched.

**To Reproduce**
1. Go to Docker tab
2. Click on jellyplex-watched and choose edit
3. Scroll down to LOGFILE
4. Edit Value to /mnt/cache/appdata/jellyplex-watched/log.log from DEFAULT /tmp/log.log

**Expected behavior**
To create log files here /mnt/cache/appdata/jellyplex-watched/log.log 

**Logs**
Traceback (most recent call last):
  File "/app/src/main.py", line 225, in main
    main_loop()
  File "/app/src/main.py", line 147, in main_loop
    logger(f"Server 1: {server_1[0].capitalize()}: {server_1[1].info()}", 0)
  File "/app/src/functions.py", line 35, in logger
    with open(f"{log_file}", "a", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/cache/appdata/jellyplex-watched/log.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 11, in <module>
    main()
  File "/app/src/main.py", line 243, in main
    logger(error, log_type=2)
  File "/app/src/functions.py", line 35, in logger
    with open(f"{log_file}", "a", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/cache/appdata/jellyplex-watched/log.log'
User is root, checking if we need to create a user and group based on environment variables
Starting JellyPlex-Watched with UID: 1000 and GID: 1000
Server 1: Plex: Plex Entertain: 1.41.2.9200-c6bbc1b53
[ERROR]: [Errno 2] No such file or directory: '/mnt/cache/appdata/jellyplex-watched/log.log'

**Type:**
 Unraid 6.12.13

**Additional context**
Docker Immediately stops unless I use the default location. I tried creating a log.log file and applying permissions but still get same error.

**Comment by luigi311** [comment]
did you create a mount for that location?

**Comment by wookie104** [comment]
Do you mean a share? I just filled in the variables for the docker

**Comment by luigi311** [comment]
not a share but a mount. You need to mount that path as that path does not exist in the container by default and if it did there would be no connection from it to your unraid machine path. I do not use unraid anymore but im sure some of the other unraid folks can point you in the right direction.

**Comment by anthonyvallone** [comment]
@wookie104  you need to map like this

i have my logs on my unraid server in `/logs/*`

`/app/.env > /mnt/cache_nvme/appdata/docker/jellyplex-watched/app/.env`
`/app/log.log > /mnt/cache_nvme/appdata/docker/jellyplex-watched/logs/log.log`
`/app/mark.log > /mnt/cache_nvme/appdata/docker/jellyplex-watched/logs/mark.log`
